name: "[WIP] Submit Scenario"
description: "Please submit your scenario using this template"
title: "New Scenario: "
labels: new-scenario
body:
  - type: markdown
    attributes:
      value: |
        ## Don't remove the `New Scenario:` prefix from the title!
        Thank you for submitting your scenario! Please fill in the form below.
  - type: dropdown
    id: type
    attributes:
      label: Scenario type
      description: What game mode is this scenario for?
      options:
        - Coop
        - Clash
        - Campaign
      default: 0
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Scenario Title
      description: What's the title of your scenario?
      placeholder: ex. Dances with Dwarves
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Author
      description: Who is the author?
    validations:
      required: true
  - type: input
    id: source
    attributes:
      label: Source
      description: Please share a link to the scenario source.
      placeholder: ex. https://discord.com/channels/740870068178649108/1239631918643941509
    validations:
      required: true
  - type: textarea
    id: story
    attributes:
      label: The Story
      description: Write 1-2 paragraphs to set the story.
      placeholder: There is a world beyond ours, filled with beasts and monsters...
    validations:
      required: true
  - type: dropdown
    id: length
    attributes:
      label: Scenario Length
      description: How many rounds is this scenario played over?
      options: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
      default: 6
    validations:
      required: true
  - type: input
    id: player-count
    attributes:
      label: Player Count
      description: Please specify the number of players.
      placeholder: ex. 2-6, 2-3, 2 or 4
    validations:
      required: true
  - type: dropdown
    id: starting-gold
    attributes:
      label: Starting Gold
      description: How much gold do the players start with?
      options: [0, 5, 10, 15, 20, 25, 30, 35, 40]
      default: 2
    validations:
      required: true
  - type: dropdown
    id: starting-bulding-materials
    attributes:
      label: Starting Building Materials
      description: How much bulding materials do the players start with?
      options: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      default: 3
    validations:
      required: true
  - type: dropdown
    id: starting-valuables
    attributes:
      label: Starting Valuables
      description: How much valuables do the players start with?
      options: [0, 1, 2, 3, 4, 5]
      default: 1
    validations:
      required: true
  - type: dropdown
    id: income-gold
    attributes:
      label: Starting Gold Income
      description: How much gold income do the players start with?
      options: [10, 15, 20, 25, 30]
      default: 0
    validations:
      required: true
  - type: dropdown
    id: income-bulding-materials
    attributes:
      label: Starting Building Materials Income
      description: How much bulding materials income do the players start with?
      options: [0, 2, 4, 6, 8, 10]
      default: 1
    validations:
      required: true
  - type: dropdown
    id: income-valuables
    attributes:
      label: Starting Valuables Income
      description: How much valuables income do the players start with?
      options: [0, 1, 2, 3, 4, 5]
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: town-buildings
    attributes:
      label: Town Buildings
      description: Which Buildings do the players start with?
      options:
        - label: Bronze Dwelling
        - label: Silver Dwelling
        - label: Gold Dwelling
        - label: City Hall
        - label: Citadel
        - label: Mage Guild
  - type: checkboxes
    id: starting-units
    attributes:
      label: Starting Units
      description: Which Units do the players start with?
      options:
        - label: A Few Bronze Units with the lowest Recruitment cost
        - label: A Pack Bronze Units with the highest Recruitment cost
        - label: A Few of each Bronze Units
        - label: A Few Silver Units with the lowest Recruitment cost
        - label: A Pack Silver Units with the highest Recruitment cost
        - label: A Few Gold Units with the lowest Recruitment cost
        - label: A Pack Gold Units with the highest Recruitment cost
    validations:
      required: true
  - type: textarea
    id: bonus
    attributes:
      label: Additional Bonus
      description: Additional bonus the players start with. Please write one bonus per line.
      placeholder: |
        Search (2) the Artifact Deck
        Search (4) the Spell Deck
    validations:
      required: false
  - type: textarea
    id: victory
    attributes:
      label: Victory Conditions
      description: What should happen for the players to win the Scenario?
      placeholder: |
        To win the Scenario, a Hero must obtain the Grail Token and bring it to their Faction Town.
        To win the Scenario, a Hero must Flag the Dragon Utopia Field.
    validations:
      required: true
  - type: textarea
    id: defeat
    attributes:
      label: Defeat Conditions
      description: Under what circumstances do the players lose the Scenario?
      placeholder: |
        One of your Towns is captured, or a Main Hero is defeated in a battle (retreat doesn't count).
    validations:
      required: true
  - type: input
    id: timed-4
    attributes:
      label: Round 4 Timed Events
      description: What happens in Round 4?
      placeholder: |
        Remove all Black Cubes from all the Water Wheels, Windmills and Mystical Gardens on the map.
    validations:
      required: false
  - type: input
    id: timed-5
    attributes:
      label: Round 5 Timed Events
      description: What happens in Round 5?
      placeholder: |
        Gain again the result of one Field with a Black Cube.
    validations:
      required: false
  - type: input
    id: timed-6
    attributes:
      label: Round 6 Timed Events
      description: What happens in Round 6?
      placeholder: |
        All Heroes gain +1 MP.
    validations:
      required: false
  - type: input
    id: timed-7
    attributes:
      label: Round 7 Timed Events
      description: What happens in Round 7?
      placeholder: |
        Repeat the Timed Event of Round 4.
    validations:
      required: false
  - type: input
    id: timed-8
    attributes:
      label: Round 8 Timed Events
      description: What happens in Round 8?
      placeholder: |
        Repeat the Timed Event of Round 5.
    validations:
      required: false
  - type: input
    id: timed-9
    attributes:
      label: Round 9 Timed Events
      description: What happens in Round 9?
      placeholder: |
        Repeat the Timed Event of Round 6.
    validations:
      required: false
  - type: input
    id: timed-10
    attributes:
      label: Round 10 Timed Events
      description: What happens in Round 10?
      placeholder: |
        Repeat the Timed Events of Rounds 4 and 5.
    validations:
      required: false
  - type: input
    id: timed-11
    attributes:
      label: Round 11 Timed Events
      description: What happens in Round 11?
      placeholder: |
        Repeat the Timed Events of Rounds 6 and 7.
    validations:
      required: false
  - type: input
    id: timed-12
    attributes:
      label: Round 12 Timed Events
      description: What happens in Round 12?
      placeholder: |
        Every player flips one Gold Unit from Pack to Few side.
    validations:
      required: false
