name: Parse new scenario
on:
  issues:
    types: [opened]

jobs:
  parse-new-scenario:
    if: ${{ startsWith(github.event.issue.title, 'New Scenario:') }}
    name: Parsing new scenario
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Print issue title
        run: echo "Hello form ${{ github.event.issue.title }}"

      - name: Save issue body
        run: echo "${{ github.event.issue.body }}" >> issue_body.txt

      - name: Parse issue
        run: |
          python .github/parse_issue.py issue_body.txt
          rm issue_body.txt
          git status

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          # token: ${{ secrets.PAT }}
          commit-message: ${{ github.event.issue.title }}
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: test-new-scenario
          delete-branch: true
          title: ${{ github.event.issue.title }}
          # body: |
          #   Update report
          #   - Updated with *today's* date
          #   - Auto-generated by [create-pull-request][1]
          #
          #   [1]: https://github.com/peter-evans/create-pull-request
          # labels: |
          #   report
          #   automated pr
          draft: true
